data:
    image: centosbase/centos66
    hostname: jenkins-data
    stdin_open: true
    tty: true
    restart: always
  volumes:
    -/var/lib/jenkins
  environment:
    -ROLE=slave
    -SSH_PASS=jenkinspassword
  command: /bin/bash
    
